# Generated by Django 3.2.12 on 2022-03-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20220211_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
